//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaDefinitivaYolito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressCounty
    {
        public string StateId { get; set; }
        public string Name { get; set; }
        public string CountyId { get; set; }
        public string CountryRegionId { get; set; }
        public string RecId { get; set; }
        public string DlvRoute { get; set; }
    }
}
