//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaDefinitivaYolito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CabeceraCarro
    {
        public CabeceraCarro()
        {
            this.Clientes = new HashSet<Clientes>();
            this.DetalleCarro = new HashSet<DetalleCarro>();
        }
    
        public int NPedido { get; set; }
        public string RutCliente { get; set; }
        public string NombreCliente { get; set; }
        public Nullable<bool> EstadoOc { get; set; }
        public string ComunaDespacho { get; set; }
        public string CalleDespacho { get; set; }
        public string ObservacionDespacho { get; set; }
        public string CostoDespacho { get; set; }
        public string RutResponsable { get; set; }
        public string ResponsableDespacho { get; set; }
        public Nullable<System.DateTime> FechaDespacho { get; set; }
        public string MontoPagado { get; set; }
        public Nullable<int> IDCliente { get; set; }
        public string ModoEntrega { get; set; }
        public string Local { get; set; }
        public string EmailCliente { get; set; }
        public string IPAdress { get; set; }
        public string tipoDocumento { get; set; }
        public Nullable<System.DateTime> FechaCarro { get; set; }
    
        public virtual ICollection<Clientes> Clientes { get; set; }
        public virtual ICollection<DetalleCarro> DetalleCarro { get; set; }
    }
}
