//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaDefinitivaYolito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarroPagado
    {
        public int IdOrden { get; set; }
        public Nullable<int> NPedido { get; set; }
        public string RutCliente { get; set; }
        public string NombreCliente { get; set; }
        public string CodigoCompraTBK { get; set; }
        public string NumTarjetaTBK { get; set; }
        public string NCuotasTBK { get; set; }
        public string FechaCompra { get; set; }
        public string Monto { get; set; }
        public Nullable<bool> EstadoOc { get; set; }
        public string TipoCuota { get; set; }
        public string EmailCliente { get; set; }
        public string tipoDocumento { get; set; }
    }
}
