//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaDefinitivaYolito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clientes
    {
        public int IDCliente { get; set; }
        public string RutCliente { get; set; }
        public string DigCliente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public Nullable<int> TelFijo { get; set; }
        public Nullable<int> TelMovil { get; set; }
        public string Direccion { get; set; }
        public string Comuna { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public Nullable<int> NPedido { get; set; }
    
        public virtual CabeceraCarro CabeceraCarro { get; set; }
    }
}
