//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaDefinitivaYolito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cotizaciones
    {
        public int IdCotiza { get; set; }
        public string NombreCliente { get; set; }
        public string Apellido { get; set; }
        public string Email { get; set; }
        public string TelefonoContacto { get; set; }
        public string Asunto { get; set; }
        public string BodyEmail { get; set; }
        public Nullable<System.DateTime> FechaCotiza { get; set; }
    }
}
