//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaDefinitivaYolito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleCarro
    {
        public int id { get; set; }
        public Nullable<int> NPedido { get; set; }
        public string ItemBarCode { get; set; }
        public string ItemName { get; set; }
        public int Cantidad { get; set; }
        public int Precio { get; set; }
        public int Subtotal { get; set; }
        public string Photo { get; set; }
        public Nullable<long> RecRefId { get; set; }
    
        public virtual CabeceraCarro CabeceraCarro { get; set; }
    }
}
