//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaDefinitivaYolito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FichaTecnica
    {
        public int ID { get; set; }
        public long RefRecId { get; set; }
        public string ItemNameAttibute { get; set; }
        public string ItemAttibute { get; set; }
    }
}
