//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaDefinitivaYolito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MarcasAsoc
    {
        public int ID { get; set; }
        public string NombreMarca { get; set; }
        public string FotoNormal { get; set; }
        public string FotoBN { get; set; }
    }
}
