//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaDefinitivaYolito.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PaginaWebEntities1 : DbContext
    {
        public PaginaWebEntities1()
            : base("name=PaginaWebEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarroPagado> CarroPagado { get; set; }
        public virtual DbSet<Nivel1> Nivel1 { get; set; }
        public virtual DbSet<Nivel2> Nivel2 { get; set; }
        public virtual DbSet<Nivel3> Nivel3 { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Clientes> Clientes { get; set; }
        public virtual DbSet<AddressCounty> AddressCounty { get; set; }
        public virtual DbSet<FichaTecnica> FichaTecnica { get; set; }
        public virtual DbSet<MarcasAsoc> MarcasAsoc { get; set; }
        public virtual DbSet<DetalleCarro> DetalleCarro { get; set; }
        public virtual DbSet<ProductosRelacionados> ProductosRelacionados { get; set; }
        public virtual DbSet<temporal> temporal { get; set; }
        public virtual DbSet<Cotizaciones> Cotizaciones { get; set; }
        public virtual DbSet<Sinonimos> Sinonimos { get; set; }
        public virtual DbSet<ProductosKit> ProductosKit { get; set; }
        public virtual DbSet<tempProdKit> tempProdKit { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<CabeceraCarro> CabeceraCarro { get; set; }
        public virtual DbSet<ProductosOferta> ProductosOferta { get; set; }
        public virtual DbSet<TablaBanner> TablaBanner { get; set; }
    }
}
