//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaDefinitivaYolito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductosKit
    {
        public int IdProd { get; set; }
        public string ItemId { get; set; }
        public string ItemName { get; set; }
        public string Clasif1 { get; set; }
        public string Clasif2 { get; set; }
        public string Clasif3 { get; set; }
        public string ConfigId { get; set; }
        public string InventSizeId { get; set; }
        public string InventColorId { get; set; }
        public string ItemBarCode { get; set; }
        public int Price { get; set; }
        public string Photo { get; set; }
        public string HighLights { get; set; }
        public string ICat3 { get; set; }
        public string Stock { get; set; }
        public string brandInternet { get; set; }
        public Nullable<long> RefRecId { get; set; }
        public string UnitWeb { get; set; }
        public Nullable<double> Factor { get; set; }
        public Nullable<int> Orden { get; set; }
    }
}
