//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PaginaDefinitivaYolito.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tempProdKit
    {
        public int IdProd { get; set; }
        public string ItemId { get; set; }
        public string ConfigId { get; set; }
        public string InventSizeId { get; set; }
        public string InventColorId { get; set; }
        public Nullable<long> RefRecId { get; set; }
    }
}
